import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import react from '@astrojs/react';
import markdoc from '@astrojs/markdoc';
import keystatic from '@keystatic/astro';
import vercel from '@astrojs/vercel/serverless';

// Sitemap is custom-generated by src/pages/sitemap.xml.ts to handle hybrid
// output mode (which @astrojs/sitemap 3.7 doesn't play nicely with).

export default defineConfig({
  site: 'https://averde.ai',
  output: 'hybrid',
  adapter: vercel(),
  integrations: [tailwind(), react(), markdoc(), keystatic()],
});
