import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import markdoc from '@astrojs/markdoc';
import keystatic from '@keystatic/astro';
import vercel from '@astrojs/vercel';

// Sitemap is custom-generated by src/pages/sitemap.xml.ts.
// output 'static' = prerender by default, opt out per-page with
// `export const prerender = false` (API routes). This replaces the old
// 'hybrid' output, which was removed in Astro 5.
// Tailwind 4 is wired via PostCSS (postcss.config.mjs), not the Vite plugin —
// the Vite plugin is incompatible with Astro 6's Rolldown-based Vite.

export default defineConfig({
  site: 'https://averde.ai',
  output: 'static',
  adapter: vercel(),
  integrations: [react(), markdoc(), keystatic()],
  // Real 301s (the old page stubs with Astro.redirect prerendered to
  // meta-refresh pages that returned 200).
  redirects: {
    '/dental': { status: 301, destination: '/industries/dental' },
    '/hvac': { status: 301, destination: '/industries/hvac' },
    '/real-estate': { status: 301, destination: '/industries/real-estate' },
  },
});
